### ISSUE TITLE
 t is undefined

### ISSUE THREAD

**Issue by unitw** [graphql-kit/graphql-voyager#203]
when im using the voyager on my website the error.
```
t is undefined
    resize svg-pan-zoom.js:651
    resize svg-pan-zoom.js:910
    resize voyager.lib.js:1597
    e voyager.lib.js:1590
```
appears and my whole website layout goes out the window.
This only happens when the website is deployed and  im opening a dialog otherwise its working as intended.

**Comment by unitw** [comment]
Any thoughts how i can prevent this behavior?

**Comment by orefalo** [comment]
recommend to close - can reproduce
