### ISSUE TITLE
Changing Schema with SDL Marks Types and Fields as Deprecated

### ISSUE THREAD

**Issue by cramhead** [graphql-kit/graphql-voyager#373]
When I change my schema by pasting SDL all types and fields are marked as deprecated. There are no deprecated fields in the schema.
<img width="395" alt="image" src="https://github.com/graphql-kit/graphql-voyager/assets/386035/c195bc65-3c39-4ecb-b9c3-1f2bd080561f">
The schema is available at `https://github.com/cramhead/nest-gql-pub-sub/blob/main/src/schema.gql` but also attached 
[here](https://github.com/graphql-kit/graphql-voyager/files/12729526/schema.gql.zip).

**Comment by meenakshi-dhanani** [comment]
The same happens for me too. I pasted a schema - https://github.com/postman-open-technologies/graphql-dcat-specs/blob/main/schemas/dcat2-ap-nl.graphql Not sure why?
