### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by RigRizz** [graphql-kit/graphql-voyager#378]
I came across this library and wanted to try it out. I can't figure out what the problem is. Is it something with the data I'm trying to enter into the SDL field in the live demo application? For example 

```
type Query {
 id: ID
}
```

Graph is generated, but when, for example I change the name for a type and enter such data in the SDL input:
```
type QueryTest {
 id: ID
}
```
I get an error in the console

![image](https://github.com/graphql-kit/graphql-voyager/assets/62600708/7f74bcb9-7d65-48cd-9b78-3c793053866e)

Can anyone explain what the problem is? It often happens that names for types are accepted in SDL input and a view is generated, but it looks like the library only accepts selected(?) names for types?

Another example:
(work)
```
type Example {
  id: ID!
  name: String
}

type Query {
  getEx: [Example]
}
```
Error (as on the screenshot):

```
type Example {
  id: ID!
  name: String
}

type Query2 {
  getEx: [Example]
}
```

**Comment by LunaticMuch** [comment]
This is correct. By default the query root type is called `Query`. You can change it, but then you need also to add the [schema definition](https://spec.graphql.org/June2018/#example-e2969)

```
schema {
  query: Query2
}
```

Look the whole paragraph on the [specs]( https://spec.graphql.org/June2018/#sec-Root-Operation-Types)
